(function () {
  window.USRWDeck.registerSlide({
    id: "historical-split",
    title: "Collaborative signals redefine relevance",
    layout: "block-three",
    mode: "core",
    modeLabel: "Block 3 · The divergence",
    duration: "18:00-21:00",
    status: "DRAFT",
    showMeta: false,
    role: "Search matches a request to content; recommendation can infer preference from patterns across people.",
    citations: ["karlgren1990algebra", "resnick1994grouplens"],
    html: [
      "<div class=\"behavior-space-slide\">",
      "  <section class=\"reaction-matrix\" aria-label=\"Illustrative table of reader reactions to items\">",
      "    <span class=\"matrix-label\">Illustrative interaction table</span>",
      "    <table>",
      "      <thead><tr><th scope=\"col\">Reader</th><th scope=\"col\">Item A</th><th scope=\"col\">Item B</th><th scope=\"col\">Item C</th><th scope=\"col\">Item D</th></tr></thead>",
      "      <tbody>",
      "        <tr><th scope=\"row\">Mia</th><td class=\"liked\">+</td><td class=\"liked\">+</td><td class=\"liked\">+</td><td class=\"disliked\">-</td></tr>",
      "        <tr class=\"target-row\"><th scope=\"row\">Noah</th><td class=\"liked\">+</td><td class=\"liked\">+</td><td class=\"unknown\">?</td><td class=\"disliked\">-</td></tr>",
      "        <tr><th scope=\"row\">Ari</th><td class=\"disliked\">-</td><td class=\"liked\">+</td><td class=\"liked\">+</td><td class=\"liked\">+</td></tr>",
      "        <tr><th scope=\"row\">Lea</th><td class=\"disliked\">-</td><td class=\"disliked\">-</td><td class=\"liked\">+</td><td class=\"liked\">+</td></tr>",
      "      </tbody>",
      "    </table>",
      "    <p class=\"matrix-key\"><span><b>+</b> liked</span><span><b>-</b> disliked</span><span><b>?</b> no rating</span></p>",
      "  </section>",
      "  <div class=\"behavior-readings\">",
      "    <section class=\"behavior-reading\" data-fragment>",
      "      <span class=\"reading-paper\">1990 · Karlgren <sup class=\"citation-marker\" data-cite=\"karlgren1990algebra\"></sup></span>",
      "      <strong>Start with an item</strong>",
      "      <p>Rank related items from how readers rated both—not from shared words.</p>",
      "      <div class=\"behavior-equation\"><i>P</i>(A,B) = &Sigma;<sub>readers</sub> relation(<i>r</i><sub>A</sub>, <i>r</i><sub>B</sub>)</div>",
      "    </section>",
      "    <section class=\"behavior-reading\" data-fragment>",
      "      <span class=\"reading-paper\">1994 · GroupLens <sup class=\"citation-marker\" data-cite=\"resnick1994grouplens\"></sup></span>",
      "      <strong>Start with a person</strong>",
      "      <p>Use similar readers' ratings to predict what this person would prefer.</p>",
      "    </section>",
      "  </div>",
      "  <p class=\"behavior-takeaway\" data-fragment>Collaborative signals make ranking possible without a query–content match.</p>",
      "</div>"
    ].join("")
  });
}());
